assertion_consumer_service_url: "https://"
assertion_consumer_logout_service_url: "https://"
issuer: "https://"
idp_entity_id: "LocalIDP"
idp_sso_target_url: "https://"
idp_slo_target_url: "https://"
idp_cert: "abcdefg"
name_identifier_format: "123456"
idp_cert_fingerprint: "abcdefg"
idp_cert_fingerprint_algorithm: "aes"
curam_landing_page_url: "https://"
saml_logout_url: "http://localhost:3000"
account_conflict_url: "https://too_many_accounts"
account_recovery_url: "https://account_recovery"
iam_login_url: "https://iam_login_url"
curam_broker_dashboard: "https://"
kp_pay_now_issuer: "https://"
kp_pay_now_url: "https://"
kp_pay_now_private_key_location: "https://"
kp_pay_now_x509_cert_location: "https://"
kp_pay_now_audience: "https://"
kp_pay_now_relay_state: "https://"