name: yard doc generation
on: push

jobs:
  yard:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: nelonoel/branch-name@v1
      - uses: ruby/setup-ruby@v1
      - name: Restore project gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: v2-${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('**/Gemfile' ) }}
          restore-keys: |
            v2-${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('**/Gemfile' ) }}
      - name: Install project gems
        run: |
          bundle config path vendor/bundle
          bundle install
      - name: Run yard
        run: bundle exec yard doc
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.YARD_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.YARD_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YARD_SECRET_ACCESS_KEY }}
          SOURCE_DIR: doc
          DEST_DIR: ${{ env.BRANCH_NAME }}