name: yard doc generation
on: push

jobs:
  yard:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/set-ruby@v1
      with:
        ruby-version: "2.5.1"
      - name: Cache Gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-rubocop-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-rubocop-${{ hashFiles('**/Gemfile.lock') }}
      - name: bundle install
        run: |
          gem update --system
          gem install bundler -v '2.0.1'
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run rubocop
        run: yard doc
